db:
    name: ENC[AES256_GCM,data:M8f1,iv:65XzAbufW2fM+Z02HsTIVtIYnYr9Y3CUjIeCgLv56cE=,tag:EN8pgBqCGUj1dS+AqfuBrQ==,type:str]
    password: ENC[AES256_GCM,data:4+sP,iv:HBxGJlRfIRS8ZPHaw5chnba8nNP+9aZ5auNMJ8XwxFE=,tag:FNO0mWou0QxsZ5rry6ZoWA==,type:str]
sops:
    kms: []
    gcp_kms:
        - resource_id: projects/lake-337312/locations/global/keyRings/cursor-keyring/cryptoKeys/cursor-key
          created_at: "2024-11-13T12:00:23Z"
          enc: CiQAoDWZq5AH1pDE66RDGpHzZp5YsuK+rmm6dH9hTRp41BkezykSSQAxlL+hBYFMLgxi0yKZWId2xjPxMF3iPeMSGSIhd3L5ZE6vw/H4cmKQA3I5az6rsH4LKPCkYMuHSc0o7InUET30pqwrqbzvPT0=
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2024-11-13T12:00:23Z"
    mac: ENC[AES256_GCM,data:itYAYeQL0SdGszlJrDIGEvfJW7tqJ0nNxa4aE/lLuJghGuqe51TQsIyfcSWiAHikUtKvmzGFnbfquf8QOHVLT9C8Ep7X4u1LyUSVoBI3SmXul+O0cmMQULkVdMS0aB/H2HzLJN8iibysF9/obFGPoXfQEsQd2rQrxipAdHA5XVA=,iv:zAjqKk29+r0ZIu4ixe0vewP+Igi21skqtVFWrPxeSDE=,tag:QmeXd2OLKHQU6Y9KXsuqGw==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.9.1
